---
namespace: dalibo
name: dolibarr
version: 1.0.0
readme: README.md
authors: [julian.vandenbroeck@dalibo.com]
description: Allow to manage the lifecycle of Dolibarr (install, upgrade, sync,...)
license: [MIT]
tags: [dolibarr, webapp, linux, php]
dependencies: {}
repository: https://github.com/dalibo/ansible-collection-dolibarr
documentation: https://github.com/dalibo/ansible-collection-dolibarr
homepage: http://www.dalibo.com
issues: https://github.com/dalibo/-ansible-collection-dolibarr/issues
