---
namespace: dalibo
name: dolibarr
version: 1.0.0
readme: README.md
authors: [julian.vandenbroeck@dalibo.com]
description: Allow to manage the lifecycle of Dolibarr (install, upgrade, sync,...)
license: [MIT]
tags: [dolibarr, webapp, linux, php]
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
