---
driver:
  name: docker
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    networks:
      - name: dolibarr
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
env:
  ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
