---
- name: install_module | Clone (using git) dolibarr module
  ansible.builtin.git:
    repo: '{{ item.repo_url }}'
    dest: /usr/local/src/{{ item.name }}_{{ item.version }}
    version: '{{ item.version }}'
- name: install_module | Copy in custom dir of Dolibarr
  ansible.posix.synchronize:
    src: /usr/local/src/{{ item.name }}_{{ item.version }}/
    dest: '{{ dolibarr_modules_directory }}/{{ item.name }}/'
    rsync_opts: [--exclude=.git/]
  delegate_to: '{{ inventory_hostname }}'
  become_user: '{{ dolibarr_http_user }}'
  become: true
- name: install_module | Set module activation action
  ansible.builtin.set_fact:
    activation_action: "{{ 'activate' if (item.activated | default(false)) else 'deactivate' }}"
- name: install_module | Activate/deactivate module
  ansible.builtin.command:
    cmd: '{{ dolibarr_module_control_script }} --data_root={{ dolibarr_main_document_root }}
      --module={{ item.class | default("mod" + item.name | capitalize) }} --action={{ activation_action }}'
  changed_when: ((manage_module.stdout | from_json).changed_modules | int) != 0
  register: manage_module
