---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify web server is running
      ansible.builtin.uri:
        url: http://localhost/
        status_code: 200
        return_content: true
        headers:
          Host: dolibarr.example.com
      register: result_get_dolibarr
    - name: Check if Dolibarr is present into response
      ansible.builtin.assert:
        that:
          - "'Dolibarr' in result_get_dolibarr.content"
          - "'18.0' in result_get_dolibarr.content"
    - name: Verify synchronized dolibarr contains file
      ansible.builtin.lineinfile:
        dest: /var/www/dolibarr.example.com_2/filefunc.inc.php
        regex: .*define\('DOL_VERSION', '18.0
        state: absent
      changed_when: false
      check_mode: true
      register: result
      failed_when: result.found == 0
