---
- name: Import playbook for apache and mariadb
  ansible.builtin.import_playbook: ../default/config_apache_and_mariadb.yml
- name: Install mariadb
  hosts: all
  vars:
    dolibarr_version: 17.0
  tasks:
    - name: Include dolibarr install
      ansible.builtin.include_role:
        name: l00ptr.dolibarr.install
    - name: Include dolibarr configure
      ansible.builtin.include_role:
        name: l00ptr.dolibarr.configure
