---
- name: install_packages_debian | Install PHP common packages
  notify: Reload apache
  ansible.builtin.package:
    state: present
    name:
      - php-intl
      - php-mbstring
      - php-json
      - php-xmlrpc
      - php-soap
      - php-soap
      - php-gd
      - php-xml
      - php-cli
      - php-zip
      - php-curl

- name: install_packages_debian | Install PHP pgsql package
  notify: Reload apache
  ansible.builtin.package:
    state: present
    name:
      - php-pgsql
  when: dolibarr_main_db_type == 'pgsql'

- name: install_packages_debian | Install PHP mysql package
  notify: Reload apache
  ansible.builtin.package:
    state: present
    name:
      - php-mysql
  when: dolibarr_main_db_type == 'mysqli'
